import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/static/navbar";
import { sahel } from "@/next-persian-fonts/sahel";
import Footer from "@/components/static/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sahel.className} antialiased relative`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
